### ISSUE TITLE
Cannot Read Property 'indexOf' of Undefined 

### ISSUE THREAD

**Issue by SiriuXProtocoL** [dappuniversity/token_sale#17]
Error handling failing due to this error

**Comment by gabefighter99** [comment]
I second this.. kinda. indexOf is not a function is the error I get

**Comment by Madeindreams** [comment]
I have fixed them by changing
`assert(error.message.indexOf('revert') >= 0, 'cannot transfer value larger than balance');`
for
`assert(error.message, 'cannot transfer value larger than balance');`

**Comment by teddy-mczieuwa** [comment]
Thank @Madeindreams I also struggled with this issue. Your solution worked for me
