### ISSUE TITLE
Error: Returned error: VM Exception while processing transaction: revert

### ISSUE THREAD

**Issue by gauravjain14** [dappuniversity/token_sale#49]
```
  Contract: DappToken
    ✓ initializes the contract with the correct values (338ms)
    ✓ sets the total supply upon deployment (259ms)
    1) transfers token ownership
    > No events were emitted


  2 passing (3s)
  1 failing

  1) Contract: DappToken
       transfers token ownership:
     Error: Returned error: VM Exception while processing transaction: revert

```

I have followed everything in the tutorial and in fact, even copied all the code over and yet I am getting this error. Don't have the slightest clue why this is happening. Any help would be appreciated. 

[Here](https://github.com/gauravjain14/EthereumDevelopment/blob/55218f9b6a122290b3d5dca96aaa64a146bfa4e4/token_sale/contracts/DappToken.sol#L42) is the link to my repo.

**Comment by vatsalvatsyayan** [comment]
Were u able to get a fix? Does the remaining part of this work as expected?

**Comment by gauravjain14** [comment]
Yes, I was able to fix it. It was a mistake on my end.

The total amount I initiated the contract with was less than what I was trying to transfer from one account to other. 

As for things working beyond that, I have completed 4 sessions, and they all work as shown (with some minor tweaks due to the Solidity API changing)
